import{useState}from 'react'
const API='https://nyando-flood-api.onrender.com'
const F=[{key:'rainfall_mm',label:'Rainfall (mm)',def:85},{key:'temperature_c',label:'Temp (C)',def:26},{key:'soil_moisture',label:'Soil Moisture %',def:55},{key:'elevation_m',label:'Elevation (m)',def:1180},{key:'ndvi',label:'NDVI',def:0.42},{key:'distance_river_km',label:'River Dist (km)',def:4}]
export default function PredictForm(){
const[vals,setVals]=useState(Object.fromEntries(F.map(f=>[f.key,f.def])))
const[result,setResult]=useState(null)
const[loading,setLoading]=useState(false)
const[error,setError]=useState(null)
const predict=async()=>{setLoading(true);setError(null);setResult(null);try{const r=await fetch(API+'/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(vals)});if(!r.ok)throw new Error('Error '+r.status);setResult(await r.json())}catch(e){setError(e.message)}finally{setLoading(false)}}
const prob=result?(result.flood_probability??result.probability??0):null
const pct=prob!==null?Math.round(prob*100):null
const col=prob>.7?'#ef4444':prob>.4?'#f59e0b':'#22c55e'
return(<section id="predict" className="section py-16 px-6 md:px-16"><p style={{fontFamily:'IBM Plex Mono',fontSize:'.7rem',color:'rgba(201,168,76,.7)',letterSpacing:'.15em',textTransform:'uppercase'}}>Live Inference</p><h2 style={{fontFamily:'Syne,sans-serif',fontSize:'1.875rem',fontWeight:700,color:'#f1f5f9',margin:'.5rem 0'}}>Run a Flood Prediction</h2><div className="grid md:grid-cols-2 gap-8 mt-6" style={{maxWidth:680}}><div className="grid grid-cols-2 gap-4">{F.map(f=>(<div key={f.key}><label className="block text-xs text-slate-400 mb-1">{f.label}</label><input type="number" step="any" value={vals[f.key]} onChange={e=>setVals(p=>({...p,[f.key]:parseFloat(e.target.value)||0}))} className="w-full rounded px-3 py-2 text-sm text-slate-100 outline-none" style={{background:'#112240',border:'1px solid rgba(201,168,76,.2)'}}/></div>))}</div><div className="rounded-xl p-6" style={{background:'#0D1E38',border:'1px solid rgba(201,168,76,.1)'}}><h3 style={{fontFamily:'Syne,sans-serif',fontWeight:600,color:'#e2e8f0',marginBottom:'1rem'}}>Prediction Output</h3>{!result&&!error&&!loading&&<p className="text-slate-500 text-sm">Adjust inputs then click Predict</p>}{loading&&<p style={{color:'#C9A84C'}} className="blink">Running model...</p>}{error&&<p className="text-red-400 text-sm">{error}</p>}{result&&(<div><div className="flex justify-between items-end mb-2"><span className="text-xs text-slate-400">Flood Probability</span><span style={{fontFamily:'Syne,sans-serif',fontSize:'1.5rem',fontWeight:700,color:col}}>{pct}%</span></div><div className="h-3 rounded-full overflow-hidden" style={{background:'#112240'}}><div className="h-full rounded-full transition-all duration-700" style={{width:pct+'%',background:col}}/></div><p className="mt-3 text-sm font-semibold" style={{color:col}}>{prob>.7?'HIGH FLOOD RISK':prob>.4?'MODERATE RISK':'LOW RISK'}</p></div>)}<button onClick={predict} disabled={loading} className="mt-6 w-full py-3 rounded font-semibold disabled:opacity-50" style={{background:'#C9A84C',color:'#060E1A',fontFamily:'Syne,sans-serif'}}>{loading?'Predicting...':'Predict'}</button></div></div></section>)}